ScrambleStrings
houseofgeeks/CP-Dictionary pull request #168
Opened 2020-10-07 04:18 UTC by ricky1812

Closes #<number>167
<Do NOT delete this template>
Description: This is a program to check if 2 strings are scrambled.

#### Checklist
<Put an x between square brackets wherever appropriate without any spaces like [x]>

- [ x] I've followed the Contributing guidelines provided in the repository.
- [ x] I've made the changes which were demanded in the linked issue.
- [ x] My code gave a clean output on debugging. (NO warnings/errors)

2020-10-07 10:26 UTC, ankiiitraj requested changes

2020-10-07 10:26 UTC, ankiiitraj commented on Scramble Strings/ScrambleString.cpp
> +       //cout<<s1<<" "<<s2<<"/";
remove this line

2020-10-07 10:26 UTC, ankiiitraj commented on Scramble Strings/ScrambleString.cpp
> +       // cout<<key;
This too.

2020-10-08 06:30 UTC, sanskarseth approved these changes

2020-10-18 06:19 UTC, merged